[options]
; Admin password for Odoo
admin_passwd = admin

; Database connection
db_host = mainline.proxy.rlwy.net
db_port = 59964
db_user = postgres
db_password = NmSUMGhtUuqrjSnGzKHxxpDGCNmlnZfx
db_name = False
db_template = template0
db_sslmode = prefer
list_db = True

; Paths
addons_path = /opt/odoo/odoo/addons,/opt/odoo/custom-addons
data_dir = /var/lib/odoo

; Server configuration
http_interface = 0.0.0.0
longpolling_port = 8072
proxy_mode = True   ; must be True for Railway

; Logging
logfile = /var/log/odoo/odoo.log
log_level = info
log_handler = :INFO

; Memory & performance
limit_memory_hard = 4684354560
limit_memory_soft = 4147483648
limit_request = 65536
limit_time_cpu = 600
limit_time_real = 1200
workers = 0
max_cron_threads = 2

; Misc
server_wide_modules = base,web
without_demo = False
unaccent = False
translate_modules = ['all']
upgrade_path =
